In [ ]:
# Data 
revenue = [14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.50]
expenses = [12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96]

In [3]:
import numpy as np

In [4]:
rv=np.array(revenue)

In [5]:
rv

array([14574.49,  7606.46,  8611.41,  9175.41,  8058.65,  8105.44,
       11496.28,  9766.09, 10305.32, 14379.96, 10713.97, 15433.5 ])

In [7]:
ex=np.array(expenses)

In [8]:
tax=0.05*rv

In [9]:
tax

array([728.7245, 380.323 , 430.5705, 458.7705, 402.9325, 405.272 ,
       574.814 , 488.3045, 515.266 , 718.998 , 535.6985, 771.675 ])

In [33]:
prof=((rv-tax)-ex)/rv

In [30]:
#prof=np.round(prof)

In [34]:
prof=prof*100

In [38]:
prof=np.round(prof)
prof

array([ 12.,  20., -48., -37., -12.,  85.,  66.,  35.,  27., -21.,   1.,
        70.])

In [39]:
mn=np.mean(prof)

In [40]:
mn

16.5

In [41]:
len(prof)

12

In [42]:
i=0
gm=[]
bm=[]
for i in prof:
    if(i>mn):
        print("good month", i)
        gm.append(i)
    else:
        print("bad month", i)
        bm.append(i)
mx=np.max(prof)
print("maximum profit is", mx)
mi=np.min(prof)
print("minimum profit is", mi)

bad month 12.0
good month 20.0
bad month -48.0
bad month -37.0
bad month -12.0
good month 85.0
good month 66.0
good month 35.0
good month 27.0
bad month -21.0
bad month 1.0
good month 70.0
maximum profit is 85.0
minimum profit is -48.0


In [43]:
gm


[20.0, 85.0, 66.0, 35.0, 27.0, 70.0]

In [44]:
bm

[12.0, -48.0, -37.0, -12.0, -21.0, 1.0]